### ISSUE TITLE
App crashes when turn on and off bluetooth 2-3 times

### ISSUE THREAD

**Issue by gbashish12556** [zebra-technologies/Scanner-SDK-for-Android#14]
java.lang.RuntimeException: Error receiving broadcast Intent { act=android.bluetooth.adapter.action.STATE_CHANGED flg=0x15000010 (has extras) } in com.zebra.scannercontrol.SDKHandler$1@4fe6903
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1942)
        at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:240)
        at android.os.Looper.loop(Looper.java:351)

**Comment by Riadzebra** [comment]
what SDK version used?
What Device and android OS ersion?
What scanner model?
are you able to replicate with Zebra Scanner control APP sample?

**Comment by Riadzebra** [comment]
any feedback ?

**Comment by Riadzebra** [comment]
issue fixed with SDK v2.6.29.0
