### ISSUE TITLE
Android 14 support needed

### ISSUE THREAD

**Issue by nero002** [zebra-technologies/Scanner-SDK-for-Android#19]
Targeting U+ (version 34 and above) disallows creating or retrieving a PendingIntent with FLAG_MUTABLE, an implicit Intent within and without FLAG_NO_CREATE and FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT for security reasons. To retrieve an already existing PendingIntent, use FLAG_NO_CREATE, however, to create a new PendingIntent with an implicit Intent use FLAG_IMMUTABLE.

	**at com.zebra.scannercontrol.USBManager.getAvailableScannersList(USBManager.java:83)**
	
	

`(HardwareRepoImpl.kt:420)_   sdkHandler.dcssdkGetAvailableScannersList(scannerTreeList)
`

java.lang.RuntimeException: Error receiving broadcast Intent { act=android.hardware.usb.action.USB_DEVICE_ATTACHED flg=0x11000010 (has extras) } in com.universalpos.data.repository.hardware.HardwareRepoImpl$usbReceiver$1@6583b25
                                   	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1919)
                                   	at android.app.LoadedApk$ReceiverDispatcher$Args.$r8$lambda$gDuJqgxY6Zb-ifyeubKeivTLAwk(Unknown Source:0)
                                   	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
                                   	at android.os.Handler.handleCallback(Handler.java:958)
                                   	at android.os.Handler.dispatchMessage(Handler.java:99)
                                   	at android.os.Looper.loopOnce(Looper.java:230)
                                   	at android.os.Looper.loop(Looper.java:319)
                                   	at android.app.ActivityThread.main(ActivityThread.java:8934)
                                   	at java.lang.reflect.Method.invoke(Native Method)
                                   	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
                                   	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
                                   Caused by: java.lang.IllegalArgumentException: com.fynd.pos.debug: Targeting U+ (version 34 and above) disallows creating or retrieving a PendingIntent with FLAG_MUTABLE, an implicit Intent within and without FLAG_NO_CREATE and FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT for security reasons. To retrieve an already existing PendingIntent, use FLAG_NO_CREATE, however, to create a new PendingIntent with an implicit Intent use FLAG_IMMUTABLE.
                                   	at android.os.Parcel.createExceptionOrNull(Parcel.java:3073)
                                   	at android.os.Parcel.createException(Parcel.java:3053)
                                   	at android.os.Parcel.readException(Parcel.java:3036)
                                   	at android.os.Parcel.readException(Parcel.java:2978)
                                   	at android.app.IActivityManager$Stub$Proxy.getIntentSenderWithFeature(IActivityManager.java:7041)
                                   	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:752)
                                   	at android.app.PendingIntent.getBroadcast(PendingIntent.java:735)
                                   	at com.zebra.scannercontrol.USBManager.getAvailableScannersList(USBManager.java:83)
                                   	at com.zebra.scannercontrol.SDKHandler.discoverAvailableScannersWithNotification(SDKHandler.java:676)
                                   	at com.zebra.scannercontrol.SDKHandler.dcssdkGetAvailableScannersList(SDKHandler.java:1505)
                                   	at com.universalpos.data.repository.hardware.HardwareRepoImpl.updateScannersList(HardwareRepoImpl.kt:420)
                                   	at com.universalpos.data.repository.hardware.HardwareRepoImpl.initializeScannerSdkAndConnect(HardwareRepoImpl.kt:413)
                                   	at com.universalpos.data.repository.hardware.HardwareRepoImpl.handleAttachedUsbDevice(HardwareRepoImpl.kt:337)
                                   	at com.universalpos.data.repository.hardware.HardwareRepoImpl.access$handleAttachedUsbDevice(HardwareRepoImpl.kt:59)
                                   	at com.universalpos.data.repository.hardware.HardwareRepoImpl$usbReceiver$1.onReceive(HardwareRepoImpl.kt:90)
                                   	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1911)
                                   	at android.app.LoadedApk$ReceiverDispatcher$Args.$r8$lambda$gDuJqgxY6Zb-ifyeubKeivTLAwk(Unknown Source:0) 
                                   	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2) 
                                   	at android.os.Handler.handleCallback(Handler.java:958) 
                                   	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                   	at android.os.Looper.loopOnce(Looper.java:230) 
                                   	at android.os.Looper.loop(Looper.java:319) 
                                   	at android.app.ActivityThread.main(ActivityThread.java:8934) 
                                   	at java.lang.reflect.Method.invoke(Native Method) 
                                   	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
                                   	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

**Comment by Riadzebra** [comment]
new SDK 2.6.22.0 will be posted around first week of August . it can be provided on request via our support help desk . https://supportcommunity.zebra.com/s/contactsupport?language=en_US

**Comment by Riadzebra** [comment]
or use https://github.com/zebra-technologies/Scanner-SDK-for-Android/tree/master/android_scanner_sdk_demo_app/BarcodeScannerLibrary

**Comment by Riadzebra** [comment]
Did you download the latest library from link i provided ?
