### ISSUE TITLE
Unable to pair DS2278 manually via latest Android SDK

### ISSUE THREAD

**Issue by Pranit-Harekar** [zebra-technologies/Scanner-SDK-for-Android#5]
**Environment:**
Android Scanner SDK version: v2.6.10.0
Android version: 10
Scanner Model: DS2278
Firmware version: CAADFS00-003-R00
Operation Mode: DCSSDK_OPMODE_BT_NORMAL

**Source Code:**
https://gist.github.com/Pranit-Harekar/548998a4f8b66fcae000ad15b81bd8f7

**Description:**
As per the manual for Scanner Android SDK, there are two ways to pair scanner -
1. Manual - scan HID Bluetooth Classic barcode provided in the getting started manual and connect scanner directly from Android device
2. Through generated pairing barcode
However, when scanner is paired using the manual approach, the SDK fails to establish connection using `dcssdkEstablishCommunicationSession` method. Please refer to the following logs -

```
I/BluetoothManager: Trying to connect to socket. Attempt = 3
W/BluetoothAdapter: getBluetoothService() called with no BluetoothManagerCallback
E/BluetoothManager: Unable to connect() socket
java.io.IOException: read failed, socket might closed or timeout, read ret: -1
at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:772)
at android.bluetooth.BluetoothSocket.readInt(BluetoothSocket.java:786)
at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java:404)
at com.zebra.scannercontrol.BluetoothManager$ConnectThread.run(BluetoothManager.java:549)
E/BluetoothManager: ConnectThread notify
E/BluetoothManager: ConnectThread notify completed
I/BluetoothManager: connect:wait completed
I/BluetoothManager: connect:Connection not successful
I/SDKHandler: connectToAvailableScanner() connMgr.connect returns false
I/BluetoothManager: setState() 2 -&gt; 1
I/BluetoothManager: ConnectThread close()
D/BluetoothSocket: close() this: android.bluetooth.BluetoothSocket@629ea2a, channel: -1, mSocketIS: android.net.LocalSocketImpl$SocketInputStream@badb01b, mSocketOS: android.net.LocalSocketImpl$SocketOutputStream@47e65b8mSocket: android.net.LocalSocket@11f8f91 impl:android.net.LocalSocketImpl@3547ef6 fd:java.io.FileDescriptor@1ed32f7, mSocketState: INIT
I/BluetoothManager: start
D/BluetoothSocket: close() this: android.bluetooth.BluetoothSocket@629ea2a, channel: -1, mSocketIS: android.net.LocalSocketImpl$SocketInputStream@badb01b, mSocketOS: android.net.LocalSocketImpl$SocketOutputStream@47e65b8mSocket: null, mSocketState: CLOSED
I/BluetoothManager: setState() 1 -&gt; 1
E/BluetoothManager: ConnectThread return
W/System: A resource failed to call close.
I/SDKHandler: connectToAvailableScanner Error occurred
D/BluetoothSocket: close() this: android.bluetooth.BluetoothSocket@629ea2a, channel: -1, mSocketIS: android.net.LocalSocketImpl$SocketInputStream@badb01b, mSocketOS: android.net.LocalSocketImpl$SocketOutputStream@47e65b8mSocket: null, mSocketState: CLOSED
```

The same issue is reproducible with the Scanner Control app v2.6.10.0. i.e. when tried to connect to a manually paired scanner, app displays “Unable to communicate with scanner” error message as shown in the attached screenshots. However when the scanner is connected through generated pairing barcode, it works as expected.

Similar issues have been reported in the past on this forum however there is no resolution provided. Kindly advice/escalate this issue. Thanks!

Refs:
https://developer.zebra.com/forum/25447
https://developer.zebra.com/forum/24946

Screenshots:
![Untitled](https://user-images.githubusercontent.com/17886017/202821355-4cdcc7d6-79c5-419a-a244-9a6c21cf7688.png)
![Untitled 1](https://user-images.githubusercontent.com/17886017/202821353-7017c816-dd97-42e6-924e-0c4995e0f076.png)

**Comment by Pranit-Harekar** [comment]
@erangazebra @zebradcs Tagging you for the visibility, thanks!

**Comment by Pranit-Harekar** [comment]
This issue has been resolved. To pair manually, scan SSI Bluetooth Classic (Discoverable) barcode 

![image](https://user-images.githubusercontent.com/17886017/202845805-b2a59a4a-874e-4692-9773-e30e27d1f385.png)

as described in [this manual](https://www.zebra.com/content/dam/zebra_new_ia/en-us/manuals/barcode-scanners/general/ds2278/ds2278-prg-en.pdf)
